"""empty message

Revision ID: 2e753bbbf9ac
Revises: b933fa9634dc
Create Date: 2018-08-12 19:15:45.905995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e753bbbf9ac'
down_revision = 'b933fa9634dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('click_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'click_count')
    # ### end Alembic commands ###
