"""empty message

Revision ID: a5f6ab49c300
Revises: 2e753bbbf9ac
Create Date: 2018-08-12 19:38:49.509510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f6ab49c300'
down_revision = '2e753bbbf9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('click_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'click_name')
    # ### end Alembic commands ###
